server:
  port: 8088 #服务端口
spring:
  application:
    name: payment-demo #应用名称

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pay-demo?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    data-password: s02w10w25

mybatis-plus:
  configuration: #sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:cn/ww/mapper/xml/*.xml

logging:
  level:
    root: info


